id: I907FB98E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T09:39:30+00:00'
last_modified: '2022-06-08T11:07:07.959431+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22186
  title: གསུང་འབུམ། འཇམ་དབྱངས་བཞད་པའི་རྡོ་རྗེ། ༼བླ་བྲང་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8E17:
      image_group_id: I1KG10669
      title: ''
      total_pages: 822
      order: 1
      base_file: 8E17.txt
    176F:
      image_group_id: I1KG10670
      title: ''
      total_pages: 892
      order: 2
      base_file: 176F.txt
    3E02:
      image_group_id: I1KG10671
      title: ''
      total_pages: 912
      order: 3
      base_file: 3E02.txt
    '6159':
      image_group_id: I1KG10672
      title: ''
      total_pages: 838
      order: 4
      base_file: 6159.txt
    902B:
      image_group_id: I1KG10673
      title: ''
      total_pages: 952
      order: 5
      base_file: 902B.txt
    D622:
      image_group_id: I1KG10674
      title: ''
      total_pages: 728
      order: 6
      base_file: D622.txt
    86FC:
      image_group_id: I1KG10675
      title: ''
      total_pages: 676
      order: 7
      base_file: 86FC.txt
    BAB3:
      image_group_id: I1KG10676
      title: ''
      total_pages: 888
      order: 8
      base_file: BAB3.txt
    96CD:
      image_group_id: I1KG10677
      title: ''
      total_pages: 1356
      order: 9
      base_file: 96CD.txt
    D2F2:
      image_group_id: I1KG10678
      title: ''
      total_pages: 694
      order: 10
      base_file: D2F2.txt
    D28B:
      image_group_id: I1KG10679
      title: ''
      total_pages: 710
      order: 11
      base_file: D28B.txt
    93D5:
      image_group_id: I1KG10680
      title: ''
      total_pages: 872
      order: 12
      base_file: 93D5.txt
    C04D:
      image_group_id: I1KG10681
      title: ''
      total_pages: 1094
      order: 13
      base_file: C04D.txt
    C1F7:
      image_group_id: I1KG10682
      title: ''
      total_pages: 828
      order: 14
      base_file: C1F7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
