id: I907FB98E
legacy_id: P009449
ocr_import_info:
  bdrc_scan_id: W22186
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T09:31:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:53:50.817778+00:00'
last_modified: 2022-09-02 04:58:49.495976
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22186
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22186
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇམ་དབྱངས་བཞད་པའི་རྡོ་རྗེ། ༼བླ་བྲང་པར་མ།༽
  author: འཇམ་དབྱངས་བཞད་པ ༠༡་ངག་དབང་བརྩོན་འགྲུས།
statistics:
  ocr_word_mean_confidence_index: 0.6616609830110657
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I1KG10669:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10669
      total_pages: 822
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10669.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6720017214716304
    legacy_id: v001
  I1KG10673:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10673
      total_pages: 952
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG10673.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6702275762359005
    legacy_id: v005
  I1KG10672:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10672
      total_pages: 838
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG10672.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.7090579248245413
    legacy_id: v004
  I1KG10675:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10675
      total_pages: 676
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG10675.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6941324486938617
    legacy_id: v007
  I1KG10677:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10677
      total_pages: 1356
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG10677.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7275255153453837
    legacy_id: v009
  I1KG10679:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10679
      total_pages: 710
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1KG10679.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6631334375901383
    legacy_id: v011
  I1KG10674:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10674
      total_pages: 728
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG10674.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7176268264861045
    legacy_id: v006
  I1KG10678:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10678
      total_pages: 694
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1KG10678.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.7037233645817148
    legacy_id: v010
  I1KG10671:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10671
      total_pages: 912
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG10671.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.7085198378861011
    legacy_id: v003
  I1KG10670:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10670
      total_pages: 892
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG10670.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6751669301428529
    legacy_id: v002
  I1KG10682:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10682
      total_pages: 828
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I1KG10682.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5746923250774957
    legacy_id: v014
  I1KG10681:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10681
      total_pages: 1094
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I1KG10681.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5777289658930959
    legacy_id: v013
  I1KG10676:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10676
      total_pages: 888
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG10676.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6320644025226965
    legacy_id: v008
  I1KG10680:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10680
      total_pages: 872
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1KG10680.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5972769542662815
    legacy_id: v012
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
